failed attempt with cgan
Considering the similarities in CGAN and CTGAN, when faced with the error, the model was changed to CTGAN which was successful so this attempt is abandoned until needed to use Kmeans for conditional formatting.

error faced:
TypeError                                 Traceback (most recent call last)
Cell In[7], line 2
      1 # Init the Conditional GAN providing the index of the label column as one of the arguments
----> 2 synth = RegularSynthesizer(modelname='cgan', model_parameters=gan_args)
      3 #synth=RegularSynthesizer(modelname = 'cgan').function(model_parameters = gan_args)
      4
      5 # Training the Conditional GAN
      6 synth.fit(data=train_data, train_arguments=train_args, num_cols=num_cols)

File e:\m2hycon\Thesis\SyntheticDataGeneration\venv\lib\site-packages\ydata_synthetic\synthesizers\regular\model.py:56, in RegularSynthesizer.__new__(cls, modelname, model_parameters, **kwargs)
     54     model=Model(modelname).function(**kwargs)
     55 else:
---> 56     model=Model(modelname).function(model_parameters, **kwargs)
     57 return model

File e:\m2hycon\Thesis\SyntheticDataGeneration\venv\lib\site-packages\ydata_synthetic\synthesizers\regular\cgan\model.py:32, in CGAN.__init__(self, model_parameters)
     30 def __init__(self, model_parameters):
     31     self._col_order = None
---> 32     super().__init__(model_parameters)

TypeError: object.__init__() takes exactly one argument (the instance to initialize)